#!/usr/bin/env python3
"""Generate an update-manifest.txt for the WorldPainter Languages updater.

Cross-platform equivalent of the -GenerateUpdateManifest switch of
tools/windows-packaging/build-windows-installer.ps1: it walks a staged application directory and
writes one file= line per file, with the SHA-256, the size, the relative path and the download URL.
"""

import argparse
import fnmatch
import hashlib
import sys
import urllib.parse
from pathlib import Path

# A release manifest covers the whole application directory, including updater.properties and the updater jar itself:
# a client that never gets those keeps the old manifest URL and the old updater forever. The updater skips the jar it
# is running from. Only the leftovers of an interrupted update are excluded, because they are not part of any release.
DEFAULT_EXCLUDES = ["*.wpupdate-tmp"]

def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            digest.update(chunk)
    return digest.hexdigest()

def is_excluded(rel: str, patterns) -> bool:
    name = rel.rsplit("/", 1)[-1]
    return any(fnmatch.fnmatch(rel, p) or fnmatch.fnmatch(name, p) for p in patterns)

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", required=True, help="Staged application directory (the jpackage 'app' input directory)")
    parser.add_argument("--version", required=True, help="Human-readable version to record in the manifest")
    parser.add_argument("--base-url", required=True, help="Base URL under which the files from --root are hosted")
    parser.add_argument("--output", default="update-manifest.txt", help="Output manifest path (default: update-manifest.txt)")
    parser.add_argument("--exclude", action="append", default=[], metavar="GLOB",
                        help="Additional glob (matched against the relative path and the file name) to exclude; may be repeated. "
                             f"Always excluded: {', '.join(DEFAULT_EXCLUDES)}")
    parser.add_argument("--delete", action="append", default=[], metavar="PATH",
                        help="Relative path the updater should delete on clients; may be repeated")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    if not root.is_dir():
        parser.error(f"--root is not a directory: {root}")
    base_url = args.base_url.rstrip("/")
    excludes = DEFAULT_EXCLUDES + args.exclude

    entries = []
    total = 0
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(root).as_posix()
        if is_excluded(rel, excludes):
            continue
        size = path.stat().st_size
        url = base_url + "/" + urllib.parse.quote(rel)
        entries.append(f"file={sha256_of(path)}\t{size}\t{rel}\t{url}")
        total += size

    if not entries:
        print("ERROR: no files found under", root, file=sys.stderr)
        return 1

    lines = [
        "# WorldPainter Languages update manifest",
        "# Generated by tools/generate_update_manifest.py",
        "format=1",
        f"version={args.version}",
        *entries,
        *(f"delete={p}" for p in args.delete),
        "",
    ]
    out = Path(args.output)
    out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {out} ({len(entries)} files, {total} bytes covered, version {args.version})")
    return 0

if __name__ == "__main__":
    sys.exit(main())
