# This file is part of WorldPainter Languages, an unofficial localization fork of
# WorldPainter (https://github.com/saplome/WorldPainter-LANGUAGES).
#
# Original work Copyright © pepsoft.org, The Netherlands.
# Modifications Copyright © 2026 saplome. This file was modified in 2026.
#
# This file remains licensed under the GNU General Public License, version 3.
# See the LICENSE file for details.

# Make sure to use the same terms as the Minecraft client uses in your language
SURVIVAL=Survival
CREATIVE=Creative
ADVENTURE=Adventure
HARDCORE=Hardcore