# Standard Swing dialog strings (UTF-8).
swing.fileChooser.lookInLabel=Look in:
swing.fileChooser.saveInLabel=Save in:
swing.fileChooser.fileNameLabel=File Name:
swing.fileChooser.filesOfTypeLabel=Files of Type:
swing.fileChooser.upFolderToolTip=Up One Level
swing.fileChooser.homeFolderToolTip=Home
swing.fileChooser.newFolderToolTip=Create New Folder
swing.fileChooser.listViewToolTip=List
swing.fileChooser.detailsViewToolTip=Details
swing.fileChooser.viewMenuToolTip=View Menu
swing.fileChooser.viewMenuAccessibleName=View Menu
swing.fileChooser.fileNameHeader=Name
swing.fileChooser.fileSizeHeader=Size
swing.fileChooser.fileTypeHeader=Type
swing.fileChooser.fileDateHeader=Date Modified
swing.fileChooser.fileAttrHeader=Attributes
swing.fileChooser.openButton=Open
swing.fileChooser.openButtonToolTip=Open Selected File
swing.fileChooser.cancelButton=Cancel
swing.fileChooser.cancelButtonToolTip=Close Dialog
swing.fileChooser.saveButton=Save
swing.fileChooser.saveButtonToolTip=Save Selected File
swing.fileChooser.updateButton=Update
swing.fileChooser.helpButton=Help
swing.fileChooser.directoryOpenButton=Open
swing.fileChooser.directoryOpenButtonToolTip=Open Selected Directory
swing.fileChooser.openDialogTitle=Open
swing.fileChooser.saveDialogTitle=Save
swing.fileChooser.acceptAllFileFilter=All Files
swing.fileChooser.newFolderButton=Create Folder
swing.fileChooser.renameFileButton=Rename
swing.fileChooser.deleteFileButton=Delete
swing.fileChooser.filterLabel=Files of Type:
swing.fileChooser.foldersLabel=Folders
swing.fileChooser.filesLabel=Files
swing.fileChooser.pathLabel=Path:
swing.fileChooser.newFolderError=Error creating new folder
swing.fileChooser.newFolder=New Folder
swing.colorChooser.ok=OK
swing.colorChooser.cancel=Cancel
swing.colorChooser.reset=Reset
swing.colorChooser.preview=Preview
swing.colorChooser.sampleText=Sample Text
swing.colorChooser.swatchesName=Swatches
swing.colorChooser.swatchesRecent=Recent:
swing.colorChooser.rgbName=RGB
swing.colorChooser.hsvName=HSV
swing.colorChooser.hslName=HSL
swing.colorChooser.cmykName=CMYK
swing.colorChooser.rgbRed=Red
swing.colorChooser.rgbGreen=Green
swing.colorChooser.rgbBlue=Blue
swing.colorChooser.rgbAlpha=Alpha
swing.colorChooser.rgbHexCode=Color Code
swing.colorChooser.hsvHue=Hue
swing.colorChooser.hsvSaturation=Saturation
swing.colorChooser.hsvValue=Value
swing.colorChooser.hsvTransparency=Transparency
swing.colorChooser.hslHue=Hue
swing.colorChooser.hslSaturation=Saturation
swing.colorChooser.hslLightness=Lightness
swing.colorChooser.hslTransparency=Transparency
swing.colorChooser.cmykCyan=Cyan
swing.colorChooser.cmykMagenta=Magenta
swing.colorChooser.cmykYellow=Yellow
swing.colorChooser.cmykBlack=Black
swing.colorChooser.cmykAlpha=Alpha
swing.optionPane.yes=Yes
swing.optionPane.no=No
swing.optionPane.ok=OK
swing.optionPane.cancel=Cancel
